name: bitmap_example
description: Demonstrates how to use the bitmap plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.13.9 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bitmap:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/doggo.jpeg
    - assets/street.jpg
