name: bitmap
description: Bitmap is a fast and minimalistic lib that heelps you to manipulate image on Flutter apps.
version: 0.1.4
homepage: https://github.com/renancaraujo/bitmap

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.13.9 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.bitmap
        pluginClass: BitmapPlugin
      ios:
        pluginClass: BitmapPlugin
